# Generated by Django 5.1 on 2024-08-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_group_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.whatsappgroup'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversations.whatsappgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.whatsappuser')),
            ],
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='members',
            field=models.ManyToManyField(to='conversations.whatsappuser'),
        ),
        migrations.CreateModel(
            name='UserWhatsAppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whatsapp_groups', models.ManyToManyField(to='conversations.whatsappgroup')),
                ('whatsapp_users', models.ManyToManyField(to='conversations.whatsappuser')),
            ],
        ),
    ]
